name: Test Static Site Generation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Deps
        run: |
          pip install -r requirements.txt

      - name: Generate Static Files
        run: |
          make html
